##############################################################################
#MediaTek Inc. (C) 2018. All rights reserved.
#Copyright Statement:
#This software/firmware and related documentation ("MediaTek Software") are
#protected under relevant copyright laws. The information contained herein is
#confidential and proprietary to MediaTek Inc. and/or its licensors. Without
#the prior written permission of MediaTek inc. and/or its licensors, any
#reproduction, modification, use or disclosure of MediaTek Software, and
#information contained herein, in whole or in part, shall be strictly
#prohibited.
#BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
#THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
#RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
#ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
#WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
#WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
#NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
#RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
#INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
#TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
#RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
#OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
#SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
#RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
#STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
#ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
#RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
#MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
#CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
#The following software/firmware and/or related documentation ("MediaTek
#Software") have been modified by MediaTek Inc. All revisions are subject to
#any receiver's applicable license agreements with MediaTek Inc.
##############################################################################
include $(KERNEL_MIXED_BUILD_PATH)/Kbuild.common

# this build is tmp solution for b/243501482,
# not support for projects don't use Android.mk.
# Should be deferred-free-helper-objs+=.. if it really needs to support
ifeq ($(LOCAL_MODULE),mtk_ion.ko)
ccflags-y += -I$(srctree)/lib
mtk_ion-objs := ion.o \
		ion_buffer.o \
		ion_dma_buf.o \
		ion_heap.o
obj-$(CONFIG_ION) += mtk_ion.o
endif

ifeq ($(LOCAL_MODULE),ion_sys_heap.ko)
obj-$(CONFIG_ION_SYSTEM_HEAP) += ion_sys_heap.o
ion_sys_heap-objs := heaps/ion_system_heap.o heaps/ion_page_pool.o
endif

ifeq ($(LOCAL_MODULE),ion_cma_heap.ko)
obj-$(CONFIG_ION_CMA_HEAP) += ion_cma_heap.o
ion_cma_heap-objs := heaps/ion_cma_heap.o
endif
