#
# Makefile for MTK wifi control device drivers.
#

# general options
EXTRA_CFLAGS      +=  -I$(srctree)/drivers/mstar2/include/sys/common
EXTRA_CFLAGS      +=  -I$(srctree)/drivers/mstar2/include
EXTRA_CFLAGS      +=  -I$(srctree)/include/linux
EXTRA_CFLAGS      +=  -I$(srctree)/drivers/mstar2/drv/gpio
# specific options
EXTRA_CFLAGS      +=


# files
obj-$(CONFIG_MTK_WIFI_CONTROL)              := mdrv_wifi_ctl.o
